<?php

namespace GoGreat\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DemoCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemoCommentRepository extends EntityRepository
{
}