<?php

namespace GoGreat\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DemoUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemoUserRepository extends EntityRepository
{
}